controller_names:
  - fake_ruka_controller

fake_ruka_controller:
    joints:
      - base_link__link_01
      - link_01__link_02
      - link_02__link_03
      - link_03__link_04
      - link_04__link_05
      - link_05__link_06

initial:
   ruka: ready
   
